install:
  - choco install gitversion.portable -pre -y

assembly_info:
  patch: false

platform:
  - Any CPU

configuration:
  - Release
 
build_script:
  - cmd: nuget restore
  - cmd: gitversion /l console /output buildserver /updateAssemblyInfo
  
  - cmd: msbuild Shouldly.sln "/p:Configuration=%CONFIGURATION%;Platform=%PLATFORM%;TargetFrameworkVersion=v3.5"
  - cmd: msbuild Shouldly.sln "/p:Configuration=%CONFIGURATION%;Platform=%PLATFORM%;TargetFrameworkVersion=v4.0"
  
  - cmd: ECHO nuget pack Shouldly.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: nuget pack Shouldly.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: appveyor PushArtifact "Shouldly.%GitVersion_NuGetVersion%.nupkg"
